[build]
  command = "npm run build"
  publish = "dist/public"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/sitemap.xml"
  to = "public/sitemap.xml"
  status = 200

[[redirects]]
  from = "/robots.txt"
  to = "public/robots.txt"
  status = 200
